[build.env]
passthrough = ["LITCRYPT_ENCRYPT_KEY", "UUID", "SLEEP", "SERVER", "PORT", "JITTER", "AES_KEY", "RUSTUP_TOOLCHAIN"]

[build.env]
passthrough = ["LITCRYPT_ENCRYPT_KEY", "UUID", "SLEEP", "SERVER", "PORT", "JITTER", "AES_KEY"]
